version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      # This port is for the WebSocket server
      - "8080:8080"
      # This port is for the Syslog server
      - "1514:1514/udp"
    # Give the container capabilities to perform network scans
    cap_add:
      - NET_ADMIN
      - NET_RAW